OOCFLAGS?=-v -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/ -L/usr/local/opt/freetype/lib/

all:
	rock $(OOCFLAGS)
	
editor:
	rock $(OOCFLAGS) --sourcepath=source editor

clean:
	rock -x

.PHONY: all editor clean
