OOCFLAGS?=-v -I/usr/local/include -L/usr/local/lib -I/usr/local/opt/freetype/include -I/usr/local/opt/freetype/include/freetype2 -L/usr/local/opt/freetype/lib -lopengl32 -lglu32

all:
	rock $(OOCFLAGS)

clean:
	rock -x

.PHONY: all clean
